project:
  type: website

website:
  title: "RNA-seq Crash Course"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Computing"
        menu:
          - computing/hpc.qmd
          - computing/isaac-ng.qmd
      - text: "Pipeline"
        menu:
          - pipeline/raw_fastqc.qmd
          - pipeline/trim_reads.qmd
          - pipeline/map_reads.qmd
  body-header: |
    ::: {.callout-warning title="alpha stage warning"}
    This website is in its alpha stage.
    All pages are under active development and are subject to change at any time without warning.
    :::

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

