project:
  type: website

website:
  title: "RNA-seq Crash Course"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Computing"
        menu:
          - computing/hpc.qmd
          - computing/isaac-ng.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
