---
title: "RNA-seq Crash Course"
date: 2025-11-24
author: "Trevor F. Freeman"
institute: "UTIA Genomics Center"
format: revealjs
---

# What will we cover?

## Intuition behind major RNA-seq analysis steps

- What are the goals of an RNA-seq analysis?
- How are short sequencing reads transformed into quantitative data?
- How is quantitative data used to test hypotheses?

## A setup for everyday analysis with literate programming

- What is literate programming?
- How can Quarto be used for literate programming?
- How does git fit into this workflow?

# What are the goals of an RNA-seq analysis?

What can we learn from an RNA-seq experiment?

## Transcriptomics is a tool for hypothesis generation

- Measure every gene in every sample to produce dataset with tens or hundreds of thousands of data points
- Apply statistical/ML methods to identify patterns in high dimensional data
- Make inferences about biological meaning, i.e. generate hypotheses

High dimensionality switches experimental paradigm to one of discovery

- "Which genes are involved?" instead of "Is gene X involved?"

## -omics methods are just techniques for answering research questions

- Specific goal(s) means easier analysis and more impactful results
- Still have data to chase vague goals

Example questions:

- Vague: Drug treated animals have changes in gene expression relative to nontreated animals
- Specific: Insulin stimulated genes are downregulated in drug treated relative to nontreated animals

